### ISSUE TITLE
Module require varnish to be operational, even locally

### ISSUE THREAD

**Issue by php4umagento** [scandipwa/persisted-query#11]
**Describe the bug**
Running setup upgrade produce error `Error flushing Varnish server. Host: "%s". PURGE response code: %s`

**To Reproduce**
1. Do not configure varnish in Magento 2
2. Run `./bin/magento setup:upgrade`

**Expected behavior**
Command finishes without any issues

**Actual behavior**
Fatal error triggered

**Comment by php4umagento** [comment]
@eli-l @alfredsgenkins please see above - this is serious blocker to deploy it in headless mode

**Comment by eli-l** [comment]
This is expected behavior. If service is not pluged - you're getting an error.
It is absolutely possible to configure Varnish in headless mode:
  bin/magento setup:config:set --http-cache-hosts=varnish
  php bin/magento config:set system/full_page_cache/varnish/access_list "127.0.0.1, app, nginx"
  php bin/magento config:set system/full_page_cache/varnish/backend_host nginx
  php bin/magento config:set system/full_page_cache/varnish/backend_port 80
  php bin/magento config:set system/full_page_cache/caching_application 2
