### ISSUE TITLE
 Error reaching Varnish

### ISSUE THREAD

**Issue by mrrobotisback** [scandipwa/persisted-query#12]
**Describe the bug**
I add in env.php of magento 2.3.2 
```'persisted-query' => [
            'redis' => [
                'host' => 'rediscache',
                'scheme' => 'tcp',
                'port' => '6379',
                'database' => '3'
            ]
        ]
```
But when run a command in console of magento in docker container all command run this:
```
Error reaching Varnish: Unable to connect to domainname:80 . Error #0: stream_socket_client(): unable to connect to domainname:80 (php_network_getaddresses: getaddrinfo failed: Name or s  
  ervice not known)  
```

**To Reproduce**
I have do only composer require and add in env.php the code.

Fragment of env file:

```
    'cache' => [
        'persisted-query' => [
            'redis' => [
                'host' => 'rediscache',
                'scheme' => 'tcp',
                'port' => '6379',
                'database' => '3'
            ]
        ]
    ],
```

The error is display when run bin/magento cache:clean or setup:upgrade

maybe i forgot to do something, do you know what ?

thanks in advance

P.S.

The problem is in this class:
src/Model/PurgeCache.php

In line 37. 
 $socketAdapter->connect($server->getHost(), $server->getPort());

Here take hostname and port 80, but i think that here need to take rediscahe no ?

**Comment by eli-l** [comment]
You're referencing Redis config describing Varnish issue. These are completely different and independant services. Varnish configuration is usually kept in the database (`core_config_data` table). 
The error you're referencing means that `domainname:80` is not accessible, might be caused by wrong port or hostname. If you're using Docker environment default name of the service (can be also used as internal domain) is `varnish`.
This is a misconfiguration, it is throwing error for a reason.
